### ISSUE TITLE
cant login on Linux

### ISSUE THREAD

**Issue by bigpodgurc** [swdotcom/swdc-atom#3]
Cant login on linux with all programs i use
(vscode atom idea pycharm) it pushes me to the page and i login and thats it

**Comment by andrewhli** [comment]
Thanks for letting us know! Right now, we don't 100% support Linux. We're looking to add support later in the month, and I'll be sure to let you know.

**Comment by brettmstevens7** [comment]
Hi @bigpodgurc. This is now fixed and you should be able to log in to your account on Linux.
