### ISSUE TITLE
CodeTime is not working in atom

### ISSUE THREAD

**Issue by kelvinninja1** [swdotcom/swdc-atom#33]
**Describe the bug**
```paste below
CodeTime is not found on the the status bar as it use to be and neither is it at the packages menu tab.
I tried disabling and enabling, uninstalling and reinstalling, updating several times but non works
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

It just Disappeared One day and that's it
1. Try using Atom '...'
2. Look down to the status bar '....'
3. Check the packages tab in the menu bar for code'....'
4. See its not showing

**Expected behavior**
```paste below
It is expected to work as usual
```

**ACTUAL RESULTS**

```paste below
CodeTime is no where to be found
```

**Screenshots**
![codeTime bug](https://user-images.githubusercontent.com/33485727/85232379-fce97200-b3ed-11ea-831b-7779aee2fdfc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
Microsoft Windows 10
 - Plugin version [e.g. Code Time v1.2.1]
From Old to Latest version Code Time v4.1.9
**Additional context**
```paste below

```

**Comment by xavluiz** [comment]
Hi, thank you for the issue update. It currently works for me but we will definitely look into this. Would you be able to capture any console errors related to code time and send these within this issue report? You can view the console logs within the menu: View -> Developer -> Toggle Developer Tools. Thank you.
Xavier

**Comment by kelvinninja1** [comment]
Oh Yh I should have added those but I think it wasn't being run on startup by atom for some reason

But I just started working 2-3 days ago, I am about to update to the latest version I hope will still work for me.

It working now, thanks to Xavier and you all.
My coding just got more interesting (;>
