### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by zhouuualexander** [swdotcom/swdc-atom#4]
I clicked the Code Time and sign in on the website, but it was still not change to a rocket.

**Comment by brettmstevens7** [comment]
Hi @zhouuualexander, could you try these steps?

- Delete the `.software` folder in your home directory
- Download the latest version of the Atom package: https://atom.io/packages/code-time (make sure you are using this version and not the old version named `Software`)
- Log in to your account via the link in the Atom menu (`Packages` > `Code Time` > `Log in...`)

The status bar will change to a rocket when you're above your average code time for that day of the week.
