### ISSUE TITLE
Slow ctrl+c after latest update

### ISSUE THREAD

**Issue by chrion02** [swdotcom/swdc-atom#5]
After the latest update the plugin slowed down ctrl+c (copy).
Open key binding resolver and test for yourself

**Comment by Bkbrawler04** [comment]
@chrion02 is this still an issue for you?

**Comment by chrion02** [comment]
@Bkbrawler04 Haven't been using the package since it stopped being problematic. You can close the issue.

**Comment by andrewhli** [comment]
Thanks @chrion02 and @Bkbrawler04 - Sorry about the bug. We fixed this issue shortly after this ticket was made and have made considerable improvements to how the package/extension works since then
