### ISSUE TITLE
Inclusion on Atom-Forked Package Repository

### ISSUE THREAD

**Issue by confused-Techie** [swdotcom/swdc-atom#96]
Hello `code-time` devs!

I'm involved with the [`Pulsar`](https://github.com/pulsar-edit) community, who is trying to build a stable fork of Atom, after the announcement of the sunset. 

One of my biggest contributions to the project is a new backend for the Package Repository Server. Through this process I've been going ahead and migrating all existing packages from Atom.io's backend to the new one.

I was hoping to include your package published on this repo, but it is currently not compatible with the new backend. 

Looking into this issue, it is because of the method your license is declared in the `package.json` file. While wanting to include your package in this migration I want it to remain true to your vision, and was wondering if you'd rather the package not be included at all, or if there is a method of restating this license field that you are comfortable with.

Whereas we could change `Reproduction of this material is strictly forbidden unless prior written permission is obtained from Software.co Technologies, Inc.`, to something along the lines below:

* `Reproduction strictly forbidden unless prior written permission from Software.co Technologies, Inc.`
* `License in LICENSE.md`
* `All Rights Reserved`
* `Apache-2.0`

If any of these is suitable please let me know. Otherwise feel free to let me know if you are uncomfortable with including this package in the new backend. 

Otherwise if no response is received before the Migration is completed, I'll ensure not to include the package.

Thank you for your time.

**Comment by mmclead** [comment]
HI @confused-Techie thanks for the interest in bringing this over.

I'll go through the options you listed and see what changes we can make.  

Will get back to you soon.

**Comment by confused-Techie** [comment]
Sounds fantastic! Thanks for responding so quickly!

**Comment by confused-Techie** [comment]
I appreciate your willingness to work with me on this one. But at this point we have completed migration and are soon to go onto steps to move past this point in our process (that is of migrating packages).

So I appreciate the time spent but will go ahead and close this issue to prevent confusion on your side.

Thanks for your time and happy developing!
